spring:
  application:
    name: mysterioustemple
  jackson:
    serializazion:
      WRITE_DATES_AS_TIMESTAMPS : false
  thymeleaf:
    cache: false
---
spring:
  profiles: postgresql-create
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
spring:
  profiles: postgresql-validate
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
