spring:
  application:
    name: mysterioustemple
  jackson:
    serializazion:
      WRITE_DATES_AS_TIMESTAMPS : false
  thymeleaf:
    cache: false
---
spring:
  profiles: h2
---
spring:
  profiles: postgresql
  datasource:
      username: jlg
      password: peakyblinders
      platform: POSTGRESQL
---
spring:
  profiles: ddl-create
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: ddl-validate
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: heroku
  datasource:
      url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}